export const siteConfig = {
  name: 'VaaniEval',
  description: 'Open-source, self-hosted evaluation workspace for production voice-agent conversations.',
  url: process.env.NEXT_PUBLIC_SITE_URL || 'https://www.vaanieval.com',
  appUrl: process.env.NEXT_PUBLIC_APP_URL || 'https://app.vaanieval.com',
  githubUrl: 'https://github.com/shubhamofbce/vaanieval',
  contactUrl: 'https://github.com/shubhamofbce/vaanieval/issues/new?title=Design%20partner%20application&labels=design-partner',
  integrationRequestUrl: 'https://github.com/shubhamofbce/vaanieval/issues/new?title=Integration%20request&body=%23%23%20Integration%20request%0A%0AWhich%20provider%20or%20platform%20would%20you%20like%20VaaniEval%20to%20support%3F%0A%0AWhat%20conversation%20data%20or%20workflow%20should%20it%20support%3F%0A%0APlease%20do%20not%20include%20credentials%2C%20private%20call%20data%2C%20or%20other%20sensitive%20information.',
}

export type BlogPost = {
  slug: string
  title: string
  description: string
  publishedAt: string
  readingTime: string
  category: string
  content: string[]
}

export const posts: BlogPost[] = [
  {
    slug: 'voice-agent-qa-production-guide',
    title: 'A practical QA process for production voice agents',
    description: 'How to replace random call sampling with a repeatable conversation review and evaluation workflow.',
    publishedAt: '2026-07-04',
    readingTime: '7 min read',
    category: 'Voice AI QA',
    content: [
      'Voice agents fail in ways that aggregate dashboards hide. A call may complete while the agent gives an unsupported answer, misses an interruption, or leaves the customer without a clear resolution.',
      'A useful QA process starts with production conversations. Import calls continuously, retain transcript and audio context, and evaluate the same small set of business-critical behaviors on every review cycle.',
      'Begin with task completion, unsupported claims, fallback quality, and latency. Define what acceptable evidence looks like for each metric. Review failed conversations with the transcript and audio together, because timing and interruption problems are often invisible in text.',
      'Treat scores as prioritization signals rather than absolute truth. Evaluator rationales should point reviewers to evidence, and uncertain or high-impact cases should remain subject to human review.',
      'Close the loop by grouping repeated failures, assigning an owner, changing the agent, and checking new production calls for regression. The outcome is not a larger dashboard; it is a shorter path from a bad call to a verified fix.',
    ],
  },
  {
    slug: 'voice-ai-evaluation-metrics',
    title: 'From voice-agent evaluation scores to fixes: a worked example',
    description: 'See how one fictional production call becomes an evidence-backed scorecard, a precise agent change, and a regression check.',
    publishedAt: '2026-07-16',
    readingTime: '6 min read',
    category: 'Evaluation',
    content: [
      'A voice-agent score is useful only when it shortens the path from a weak call to a verified improvement. This worked example follows one fictional appointment-booking conversation through VaaniEval\'s current scorecard: task completion, intent understanding, required-information capture, and human-like delivery.',
      'The conversation is synthetic and deliberately small. It does not represent a customer or a benchmark. Its purpose is to show the reasoning chain a production team can reuse: define the expected outcome, inspect the evidence, identify the weakest behavior, make one targeted change, and evaluate new calls for regression.',
      '## The fictional call',
      '**Caller:** I need to move my dental cleaning to Tuesday morning.',
      '**Agent:** I can help with that. What time on Tuesday works for you?',
      '**Caller:** Anything before eleven.',
      '**Agent:** I am sorry, but I cannot access the scheduling system right now. I am sorry for the inconvenience. Please call us again later and we will help you.',
      '**Caller:** So my existing appointment is still booked?',
      '**Agent:** Please call us again later. Is there anything else I can help you with?',
      'At a glance, the agent understood the request and remained polite. A generic completion dashboard might still classify the call as handled because the intent was detected and the conversation ended normally. The customer outcome tells a different story: no appointment was moved, the original booking was never confirmed, and no safe next step was created.',
      '## Step 1: define success before scoring',
      'For this workflow, task completion should not mean that the agent discussed rescheduling. It should mean that the appointment was moved and the caller received confirmation. If the scheduling tool is unavailable, the approved fallback should preserve the existing booking, capture the caller\'s preferred window and contact details, and create a clear handoff for staff.',
      'This definition matters because an evaluator cannot reliably infer a business outcome from conversational fluency alone. Teams should write the completion condition in operational language that a reviewer can verify from the transcript, tool result, or provider metadata.',
      '## Step 2: score the four current metrics',
      '- **Task completion — 20/100.** The requested appointment change did not happen. The agent also failed to create an alternative path to completion. Evidence: “Please call us again later.”',
      '- **Intent understanding — 90/100.** The agent correctly recognized that the caller wanted to move an existing cleaning to Tuesday before 11:00. The failure occurred after understanding, so rewriting intent detection would not address the main problem.',
      '- **Required-information capture — 35/100.** The agent captured the preferred day and time window but did not confirm the caller\'s identity, the existing appointment, or a callback number. Those fields would be necessary for a human handoff.',
      '- **Human-like delivery — 55/100.** The wording was grammatically clear, but the repeated apology and repeated “call us again later” response made the interaction feel scripted. This is the higher-is-better display score; reviewers should still use the transcript and available audio context before changing delivery behavior.',
      'The scores alone are not the diagnosis. The rationale and conversation evidence explain why the result is weak. In this call, task completion is the weakest business behavior, while the high intent score shows where not to spend engineering time.',
      '## Step 3: map evidence to one targeted change',
      'The primary fix belongs in the scheduling-failure branch, not in the general prompt. When the scheduling tool is unavailable, the agent should follow an explicit recovery sequence:',
      '- State that the appointment has not been changed.',
      '- Confirm whether the existing appointment remains active using available tool state or an approved uncertainty statement.',
      '- Collect the minimum fields required for a staff callback.',
      '- Repeat the requested date and time window back to the caller.',
      '- Create the handoff through the configured workflow, or explain the exact next step if no handoff tool exists.',
      'A revised response might say: “I could not reach the scheduling system, so I have not changed your appointment. I have Tuesday before 11:00 as your preferred window. May I confirm the best callback number so the scheduling team can follow up?”',
      'That response does not pretend the original task succeeded. It makes the system state clear, preserves the caller\'s preference, and moves the conversation toward a recoverable outcome. Whether the agent can actually create the callback must be verified through the configured workflow rather than assumed from the wording.',
      '## Step 4: verify the change without moving the goalposts',
      'After changing the failure branch, keep the original success definition and scorecard stable. Re-run a small representative set that includes a successful reschedule, a scheduling outage, an ambiguous time request, and a caller who declines a callback. Then review new production conversations as they arrive.',
      'For each call, ask:',
      '- Did task completion improve because the outcome improved, or only because the response sounded more confident?',
      '- Did the agent retain correct intent understanding?',
      '- Did it collect only the information required for the handoff?',
      '- Did the new recovery wording reduce repetition without hiding uncertainty?',
      'Compare evaluator judgments with human review on the calls that matter most. If reviewers consistently disagree with the scores, adjust the rubric or evidence requirements before changing thresholds. A threshold is useful only after the team agrees on what the metric means in its own workflow.',
      '## Add broader signals only when they change a decision',
      'Unsupported claims, fallback quality, latency, interruptions, silence, and premature termination can all matter in voice-agent QA. They should be added when the team can define their evidence and connect a failure to an owner. Availability of operational signals also depends on the voice provider and the fields captured for each call.',
      'Start with a small stable scorecard, then segment trends by agent, workflow, provider, and time period. Aggregates identify where performance changed; the individual conversation, rationale, and evidence explain what to fix.',
      '## The reusable score-to-fix loop',
      '- Define the customer and business outcome before evaluating the call.',
      '- Score a small set of distinct behaviors instead of relying on one opaque quality number.',
      '- Attach a rationale and specific conversation evidence to every score.',
      '- Use the weakest relevant behavior to choose one prompt, tool, workflow, or policy change.',
      '- Evaluate representative and new production calls with the same definitions.',
      '- Keep human review for uncertain, high-impact, or disputed results.',
      '[Explore the broader voice-agent evaluation metrics guide](/resources/evaluation-metrics)',
      '[Help shape VaaniEval as a design partner](/design-partners)',
    ],
  },
  {
    slug: 'self-hosted-voice-ai-evaluation',
    title: 'Self-Hosted vs. Closed-Source Voice AI Evaluations: A Compliance and Privacy Analysis',
    description: 'How closed-source SaaS evaluation tools expose sensitive call data, and how a self-hosted open-source framework like VaaniEval secures HIPAA, GDPR, and PCI compliance.',
    publishedAt: '2026-07-04',
    readingTime: '10 min read',
    category: 'Compliance & Security',
    content: [
      'Evaluating production voice AI agents requires capturing, processing, and analyzing high-fidelity audio streams and conversation transcripts. In highly regulated sectors—such as healthcare, financial services, insurance, and telecommunications—these datasets are subject to stringent legal and security frameworks.',
      'This analysis evaluates the compliance advantages of the self-hosted, open-source approach represented by **VaaniEval** compared to closed-source Software-as-a-Service (SaaS) alternatives.',
      '## The Compliance Minefield of Voice AI Observability',
      'Voice data is uniquely sensitive. Unlike static database records or text-only chatbot logs, voice interactions pose multi-dimensional data privacy risks:',
      '- **Biometric Identifiability (GDPR Classifications)**: Voiceprints, tone, cadence, and vocal characteristics are classified as biometric data. Under frameworks like the GDPR, processing biometric data for identification purposes carries strict consent requirements and high regulatory penalties.',
      '- **Unstructured PII and PHI**: During voice interactions, customers frequently speak Protected Health Information (PHI) or Personally Identifiable Information (PII) such as Social Security Numbers, credit card numbers, dates of birth, and home addresses. Unlike structured fields, this information cannot be easily isolated without transcribing and scanning the entire audio file.',
      '- **The Sub-Processor Chain Multiplier**: A typical SaaS voice AI stack involves multiple hops: Customer Voice -> Voice Gateway (Vapi/ElevenLabs) -> Evaluation SaaS -> Evaluator LLM (OpenAI/Anthropic). For every third-party SaaS introduced, the organization must perform vendor risk assessments, sign legal agreements, and audit sub-processors.',
      '## Core Compliance Frameworks & Impact on Voice AI',
      'Let us review the key regulatory frameworks governing voice data:',
      '- **HIPAA (Health Insurance Portability & Accountability Act)**: Any audio or transcript containing health conditions, patient names, or medical records is PHI. SaaS providers must sign a Business Associate Agreement (BAA). Standard SaaS pricing models often lock BAAs behind expensive enterprise tiers.',
      '- **GDPR (General Data Protection Regulation - EU 2016/679)**: Audio recordings contain biometric data. If data is stored on a US-based SaaS database without a robust data transfer agreement (e.g., standard contractual clauses), it violates data transfer restrictions. Data deletion requests must propagate to all backups and sub-processors.',
      '- **PCI-DSS v4.0 (Payment Card Industry Data Security Standard)**: Voice agents capturing payment info in audio or transcripts bring the evaluation platform into the PCI scope. Audio recordings containing cardholder data must be encrypted and redacted to prevent accidental storage of CVV/PAN.',
      '- **SOC 2 Type II (Security, Confidentiality, & Privacy)**: Enterprise purchasing teams require third-party SaaS vendors to have an active SOC 2 Type II report. Startup SaaS providers often only have SOC 2 Type I or lack audits entirely, delaying procurement for months.',
      '## Closed-Source Voice AI Eval Providers: How They Deal with Compliance',
      'A growing ecosystem of closed-source startups and generalist LLM evaluation tools focus on voice AI evaluations and simulation. However, their closed SaaS architecture introduces specific compliance bottlenecks.',
      'Many SaaS providers like **Hamming AI**, **Coval**, **Maxim AI**, **Braintrust**, and **Tuner** have introduced features to cope with data privacy. For example, Braintrust offers a hybrid enterprise tier where evaluation data is stored in the customer\'s cloud storage (like AWS S3), while the control plane remains SaaS. Hamming AI and Maxim AI offer SOC 2 compliance and custom enterprise BAAs for HIPAA compliance. Tuner and Roark rely on client-side data masking before ingestion.',
      'However, these SaaS compliance mechanisms introduce significant friction:',
      '- **Prolonged Procurement Cycles**: Security reviews for SaaS platforms processing voice data typically take 3 to 6 months as teams audit the vendor\'s SOC 2, penetration test reports, sub-processors, and disaster recovery plans.',
      '- **Hidden Sub-processors**: SaaS eval platforms run evaluations using external LLM APIs (e.g., OpenAI, Anthropic). The customer is forced to inherit the vendor\'s sub-processors, multiplying the compliance risk.',
      '- **Data Training Leakage**: Many SaaS platforms retain user data to improve their internal algorithms and evaluator models. Preventing this requires custom contractual carve-outs.',
      '- **Data Residency Violated**: Ingested calls are stored in the SaaS vendor\'s centralized region (usually US-East), violating strict regional data residency rules in the EU, Canada, or APAC.',
      '## The Self-Hosted Paradigm: How VaaniEval Streamlines Compliance',
      'VaaniEval\'s open-source, self-hosted model addresses compliance concerns by shifting data control back to the enterprise.',
      '[VPC_DIAGRAM]',
      '### 1. Data Residency & Complete Perimeter Control',
      'Because VaaniEval is self-hosted, all conversation transcripts, audio playback streams, and evaluation metadata remain inside the enterprise\'s private network boundary (e.g., AWS, GCP, Azure, or local bare-metal servers). No data is telemetry-shipped to a third-party startup server. Supported databases (SQLite and PostgreSQL) run locally or on a private managed instance (e.g., AWS RDS or self-hosted Neon). The enterprise controls access rules, backups, and network policies.',
      '### 2. Direct Integration with Compliant LLM Endpoints',
      'SaaS evaluation platforms act as middlemen, routing your raw conversations to LLMs. VaaniEval cuts out the intermediary. By setting **CREDENTIAL_ENCRYPTION_KEY** and **OPENAI_API_BASE** in the backend configuration, evaluations can route directly to Azure OpenAI Service (with zero data retention guarantees) or to self-hosted models running via vLLM / Ollama inside the same VPC.',
      '### 3. Open Source Extensibility for Data Redaction',
      'Because VaaniEval is open-source (MIT License), developers have full access to customize the ingestion and storage layers. Developers can modify the provider adapters to scrub PII/PHI (like names, telephone numbers, and account numbers) before storing transcripts in the database. Furthermore, enterprises can implement automatic retention limits, deleting audio files from storage after scoring is complete while keeping only anonymized scores, fulfilling GDPR\'s data minimization principles.',
      '## Security & Compliance Deployment Blueprint',
      'To deploy VaaniEval in a fully compliant enterprise environment, follow this architectural setup:',
      '- **Step 1: Network Isolation**: Deploy the frontend static assets and backend FastAPI container inside a Private Subnet of your Virtual Private Cloud (VPC). Use an Internal Application Load Balancer (ALB) to restrict access to employees on the corporate VPN/Tailscale network.',
      '- **Step 2: Database and Storage Security**: Deploy a managed PostgreSQL database with Encryption at Rest enabled. Store media files (voice recordings) in an enterprise-managed private bucket (e.g., AWS S3) configured with IAM Roles and Object Lifecycle Policies to auto-delete audio files after 14 days.',
      '- **Step 3: Zero-Retention LLM Routing**: Configure your backend environment variables to route evaluations only to zero-retention or private endpoints, ensuring HIPAA BAA coverage is maintained.',
      'By leveraging VaaniEval as a self-hosted, open-source workspace, organizations eliminate third-party SaaS risks, enforce data residency, integrate with approved LLMs, and inspect their code, accelerating their time-to-market.'
    ],
  },
]
